### ISSUE TITLE
mDNS is unreliable

### ISSUE THREAD

**Issue by twobraids** [mozilla-iot/thing-url-adapter#34]
I'm finding that mDNS is very unreliable, now fewer than 1 out of 10 times will the Things Gateway find my things via mDNS.  I usually have to resort to typing in the URL myself, this usually works.  However, if the thing being added via URL has more than one thing in it, the result is always a fail with a "invalid thing description" error.  The example in the images below is an attempt to pair the `webthing-python/examples/multiple-things.py` example.
![mdns-fail](https://user-images.githubusercontent.com/581227/39400365-b6ab3172-4ae3-11e8-989d-17d4fcc966d5.png)
![mdns-fail2](https://user-images.githubusercontent.com/581227/39400367-ba596ea6-4ae3-11e8-83c0-f5acad593923.png)
![mdns-fail3](https://user-images.githubusercontent.com/581227/39400369-c3600140-4ae3-11e8-99a5-36566796bf80.png)

**Comment by twobraids** [comment]
I can understand that debugging will be difficult for mDNS.  I've got no other problems on my network with mDNS services - the Apple devices find and communicate with the Linux machines and vice versa without any appreciable trouble. 

As for the multi-device server problem, we need to make the error message more useful and then document how to add the devices piecemeal.

**Comment by mrstegeman** [comment]
@twobraids Can you post a log somewhere that has a failed mDNS discovery? I'd like to see if there are any relevant errors.

**Comment by mrstegeman** [comment]
I see the same thing on my Mac, but I know mine is because OS X is waiting for me to approve of Python listening on a port before it will actually start listening. We need to do one (or both) of the following:

1. Delay a bit before starting the mDNS broadcast in the webthing-X libraries.
2. Handle this error gracefully in `thing-url-adapter` and retry the connection a couple of times.
