### ISSUE TITLE
Multi-frequency wifi and mDNS

### ISSUE THREAD

**Issue by hobinjk** [mozilla-iot/thing-url-adapter#53]
As reported by @bromagosa, there's a potential issue with some routers where if you have a 2.4 GHz and a 5 GHz network with the same SSID the Gateway may be connected to only one of those networks and be unable to discover anything on the other frequency.

It remains to be decided whether this is a router issue or something we can mitigate in this adapter/on the gateway.

**Comment by bromagosa** [comment]
I should point out that my two frequencies have different SSIDs, but they share the same local network and IP space.

**Comment by benfrancis** [comment]
> I should point out that my two frequencies have different SSIDs, but they share the same local network and IP space.

If they share the same IP range then a device using one frequency should be able to talk to a device using the other. If not then that sounds like a router bug?

My home router came configured with 2.4Ghz and 5Ghz access points sharing the same SSID and password so clients which support both tend to switch to whichever has the strongest signal. I changed the SSID of one of them in the end because some WiFi devices were having problems with the 5Ghz AP and I wanted them to only connect to the 2.4Ghz one. But devices connected via 2.4GHz should be able to talk to devices connected via 5GHz, in the same way that WiFi devices can talk to Ethernet devices using the same IP range.

**Comment by bromagosa** [comment]
They can talk to each other, it's just that they're not discoverable over
mdns unless both the gateway and the webThing are on the same SSID.

Entering the webThing IP manually on the gateway does work, it's just the
discovery mechanism that doesn't.
